server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jeongyuneo
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  profiles:
    include: secret

kakao:
  api:
    key: ${kakao.api.secret.key}
