drop table if exists blog_search CASCADE;

create table blog_search
(
    blog_search_id   bigint generated by default as identity,
    created_at       timestamp,
    deleted          boolean not null,
    last_modified_at timestamp,
    count            integer not null,
    keyword          varchar(255),
    primary key (blog_search_id)
)
